// DO NOT EDIT - THIS FILE IS GENERATED
//
// Generated by a Python script in scripts/generate_id_tagging_schema.py.

pub fn is_area<'a>(closed: bool, tags: impl Iterator<Item = (&'a str, &'a str)>) -> bool {
    if !closed {
        return false;
    }

    for (key, value) in tags {
        if key == "area" {
            match value {
                "yes" => return true,
                "no" => return false,
                _ => {}
            }
        }

        // TODO: Port the rest of the iD logic to find out whether this is an area.
        let _key = remove_lifecycle_prefix(key);
    }

    false
}

fn remove_lifecycle_prefix(key: &str) -> &str {
    if let Some((prefix, rest)) = key.split_once(':')
        && matches!(
            prefix,
            "abandoned"
                | "construction"
                | "demolished"
                | "destroyed"
                | "dismantled"
                | "disused"
                | "intermittent"
                | "obliterated"
                | "planned"
                | "proposed"
                | "razed"
                | "removed"
                | "was"
        )
    {
        rest
    } else {
        key
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_remove_lifecycle_prefix() {
        assert_eq!(remove_lifecycle_prefix("planned:highway"), "highway");
        assert_eq!(remove_lifecycle_prefix("razed:highway"), "highway");
        assert_eq!(remove_lifecycle_prefix(""), "");
        assert_eq!(remove_lifecycle_prefix("foo"), "foo");
        assert_eq!(remove_lifecycle_prefix("foo:"), "foo:");
        assert_eq!(remove_lifecycle_prefix("foo:bar"), "foo:bar");
        assert_eq!(remove_lifecycle_prefix("foo:bar:"), "foo:bar:");
        assert_eq!(remove_lifecycle_prefix("foo:bar:baz"), "foo:bar:baz");
    }
}
