// DO NOT EDIT - THIS FILE IS GENERATED
//
// Generated by a Python script in scripts/generate_id_tagging_schema.py,
// from data at pkg:github/openstreetmap/id-tagging-schema@v7.0.1
// which is released under the ISC license.

pub fn is_area<'a>(closed: bool, tags: impl Iterator<Item = (&'a str, &'a str)>) -> bool {
    if !closed {
        return false;
    }

    let mut has_area_tag = false;
    for (key, value) in tags {
        if key == "area" {
            match value {
                "yes" => return true,
                "no" => return false,
                _ => {}
            }
        }

        // For any tags other than `area`, we don’t return immediately.
        // At this point, we don’t know if the iteration will later yield
        // `area=no`, which should win over any tag heuristics.
        //
        // Alternatively, we could do _two_ separate passes over the tags,
        // like the iD editor does in its JavaScript sources. However,
        // this has a (small) performance cost, which we can avoid by deciding
        // on area-ness in a single pass over the tags.

        // Surprisingly, it looks like not all keys in the `areaKeys` dictionary
        // of the iD editor are strictly _keys_ in the OSM sense. One single
        // entry is actually a _pattern_, for `addr:*`. From the  iD source code,
        // it’s not obvious if iD actually checks for prefixes; this might get
        // silently ignored (because looking up `addr:street` in a JavaScript
        // dictionary containing something for `addr:*` will not find anything).
        //
        // From a real-world perspective, it seems reasonable to interpret
        // OSM features with addresses as areas, not lines. Therefore, we test
        // for `addr:` prefixes, thus deviating from iD’s behavior, assuming
        // this is actually a bug in the iD editor.
        // https://github.com/openstreetmap/id-tagging-schema/issues/2623#issuecomment-5202324005
        if key.starts_with("addr:") {
            // `addr:*` in exception table
            has_area_tag = true;
            continue;
        }

        match remove_lifecycle_prefix(key) {
            "allotments"
            | "animal"
            | "area:highway"
            | "bridge:support"
            | "building"
            | "building:part"
            | "cemetery"
            | "club"
            | "community_centre"
            | "craft"
            | "education"
            | "emergency"
            | "healthcare"
            | "industrial"
            | "internet_access"
            | "junction"
            | "landuse"
            | "office"
            | "pipeline"
            | "place"
            | "police"
            | "polling_station"
            | "residential"
            | "seamark:harbour:category"
            | "seamark:type"
            | "shop"
            | "telecom" => has_area_tag = true,
            "advertising" if !matches!(value, "billboard" | "poster_box" | "sign" | "totem") => {
                has_area_tag = true
            }
            "aerialway"
                if !matches!(
                    value,
                    "cable_car"
                        | "chair_lift"
                        | "drag_lift"
                        | "gondola"
                        | "goods"
                        | "j-bar"
                        | "magic_carpet"
                        | "mixed_lift"
                        | "platter"
                        | "rope_tow"
                        | "t-bar"
                        | "zip_line"
                ) =>
            {
                has_area_tag = true
            }
            "aeroway"
                if !matches!(
                    value,
                    "jet_bridge" | "parking_position" | "runway" | "taxiway"
                ) =>
            {
                has_area_tag = true
            }
            "amenity" if !matches!(value, "bench" | "bicycle_parking" | "weighbridge") => {
                has_area_tag = true
            }
            "attraction"
                if !matches!(
                    value,
                    "dark_ride"
                        | "log_flume"
                        | "river_rafting"
                        | "summer_toboggan"
                        | "train"
                        | "water_slide"
                ) =>
            {
                has_area_tag = true
            }
            "boundary" => {
                if value != "administrative" {
                    has_area_tag = true
                }
            }
            "ceremonial_gate" if !matches!(value, "paifang" | "torii") => has_area_tag = true,
            "golf" if !matches!(value, "cartpath" | "hole" | "path") => has_area_tag = true,
            "historic" => {
                if value != "ruins" {
                    has_area_tag = true
                }
            }
            "indoor" if !matches!(value, "corridor" | "wall") => has_area_tag = true,
            "leisure" if !matches!(value, "slipway" | "track") => has_area_tag = true,
            "man_made"
                if !matches!(
                    value,
                    "breakwater"
                        | "carpet_hanger"
                        | "ceremonial_gate"
                        | "crane"
                        | "cutline"
                        | "dyke"
                        | "embankment"
                        | "gantry"
                        | "geoglyph"
                        | "goods_conveyor"
                        | "groyne"
                        | "pier"
                        | "pipeline"
                        | "quay"
                        | "video_wall"
                        | "yes"
                ) =>
            {
                has_area_tag = true
            }
            "military" => {
                if value != "trench" {
                    has_area_tag = true
                }
            }
            "natural"
                if !matches!(
                    value,
                    "arete"
                        | "bay"
                        | "cliff"
                        | "coastline"
                        | "ridge"
                        | "strait"
                        | "tree_row"
                        | "valley"
                ) =>
            {
                has_area_tag = true
            }
            "piste:type"
                if !matches!(
                    value,
                    "downhill"
                        | "hike"
                        | "ice_skate"
                        | "nordic"
                        | "ski_jump"
                        | "skitour"
                        | "sled"
                        | "sleigh"
                ) =>
            {
                has_area_tag = true
            }
            "playground"
                if !matches!(
                    value,
                    "activitypanel"
                        | "balancebeam"
                        | "basketswing"
                        | "bridge"
                        | "climbingwall"
                        | "hopscotch"
                        | "horizontal_bar"
                        | "seesaw"
                        | "slide"
                        | "structure"
                        | "swing"
                        | "tunnel_tube"
                        | "water"
                        | "zipwire"
                ) =>
            {
                has_area_tag = true
            }
            "power" if !matches!(value, "cable" | "line" | "minor_line" | "portal") => {
                has_area_tag = true
            }
            "public_transport" => {
                if value != "platform" {
                    has_area_tag = true
                }
            }
            "roller_coaster" if !matches!(value, "support" | "track") => has_area_tag = true,
            "tourism" if !matches!(value, "artwork" | "attraction") => has_area_tag = true,
            "waterway"
                if !matches!(
                    value,
                    "canal"
                        | "dam"
                        | "ditch"
                        | "drain"
                        | "fish_pass"
                        | "lock_gate"
                        | "river"
                        | "stream"
                        | "tidal_channel"
                        | "weir"
                ) =>
            {
                has_area_tag = true
            }
            _ => {}
        }
    }

    has_area_tag
}

fn remove_lifecycle_prefix(key: &str) -> &str {
    if let Some((prefix, rest)) = key.split_once(':')
        && matches!(
            prefix,
            "abandoned"
                | "construction"
                | "demolished"
                | "destroyed"
                | "dismantled"
                | "disused"
                | "intermittent"
                | "obliterated"
                | "planned"
                | "proposed"
                | "razed"
                | "removed"
                | "was"
        )
    {
        rest
    } else {
        key
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_is_area() {
        // If a way is not closed, it is never an area, no matter how it is tagged.
        assert_eq!(is_area(false, [("area", "yes")].into_iter()), false);
        assert_eq!(is_area(true, [("area", "yes")].into_iter()), true);
        assert_eq!(is_area(true, [("area", "no")].into_iter()), false);

        // By default, a closed way is not an area, unless the tags say otherwise.
        assert_eq!(is_area(true, [].into_iter()), false);
        assert_eq!(is_area(true, [("foo", "bar")].into_iter()), false);

        // Should handle allowlists and denylists.
        assert_eq!(is_area(true, [("aerialway", "pylon")].into_iter()), true);
        assert_eq!(
            is_area(true, [("aerialway", "pylon"), ("area", "no")].into_iter()),
            false
        );
        assert_eq!(
            is_area(true, [("aerialway", "pylon"), ("area", "yes")].into_iter()),
            true
        );
        assert_eq!(is_area(true, [("aerialway", "goods")].into_iter()), false);
        assert_eq!(
            is_area(true, [("aerialway", "goods"), ("area", "no")].into_iter()),
            false
        );
        assert_eq!(
            is_area(true, [("aerialway", "goods"), ("area", "yes")].into_iter()),
            true
        );

        // Should recognize lifecycle prefixes, similar to how iD does it in its codebase.
        assert_eq!(
            is_area(true, [("planned:aerialway", "pylon")].into_iter()),
            true
        );
        assert_eq!(
            is_area(true, [("planned:aerialway", "goods")].into_iter()),
            false
        );
        assert_eq!(is_area(true, [("razed:building", "yes")].into_iter()), true);
    }

    #[test]
    fn test_remove_lifecycle_prefix() {
        assert_eq!(remove_lifecycle_prefix("planned:highway"), "highway");
        assert_eq!(remove_lifecycle_prefix("razed:highway"), "highway");
        assert_eq!(remove_lifecycle_prefix(""), "");
        assert_eq!(remove_lifecycle_prefix("foo"), "foo");
        assert_eq!(remove_lifecycle_prefix("foo:"), "foo:");
        assert_eq!(remove_lifecycle_prefix("foo:bar"), "foo:bar");
        assert_eq!(remove_lifecycle_prefix("foo:bar:"), "foo:bar:");
        assert_eq!(remove_lifecycle_prefix("foo:bar:baz"), "foo:bar:baz");
    }
}
