# SPDX-FileCopyrightText: 2026 Sascha Brawer <sascha@brawer.ch>
# SPDX-License-Identifier: MIT

name: Tests

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Containerfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Containerfile'

permissions: {}

jobs:
  build:
    name: Build (container)
    runs-on: ubuntu-latest
    permissions: {}

    steps:
    - name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Install podman
      run: |
        sudo apt-get install -y podman
        podman --version
    - name: Build container
      run: |
          mkdir artifacts
          podman build -t test-container  \
              --build-arg BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")  \
              --volume $(pwd)/artifacts:/artifacts                          \
              -f Containerfile .
