name: Tests

on:
  merge_group:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Execute unit and integration tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions: {}

    env:
      RUSTC_WRAPPER: "sccache"
      SCCACHE_GHA_ENABLED: "true"

    steps:
    - name: Set up shared compilation cache
      uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba  # v0.0.11
    - name: Check out repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
    - name: Install protobuf compiler and tippecanoe
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler tippecanoe
        protoc --version
        tippecanoe --version
    - name: Install Rust coverage tool
      uses: taiki-e/install-action@6c6fd71fe4fb72c3697d269963d0e15df8adedad # v2.85.10
      with:
        tool: cargo-llvm-cov
    - name: Fetch Rust dependencies
      run: cargo fetch --locked
    - name: Check formatting
      run: cargo fmt --check
    - name: Build
      run: cargo build --locked
    - name: Run tests
      run: |
        cargo llvm-cov test --cobertura --locked --verbose --output-path cobertura.xml
    - name: Look for common mistakes
      run: cargo clippy --locked --all-targets -- -D warnings
    - name: Upload test coverage to Coveralls
      with:
        fail-on-error: false  # not critical when coveralls.io is down
      uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329  # v2.3.8
